# Release Keystore Properties
RELEASE_STORE_FILE=./PopcornKeys.jks
RELEASE_KEY_ALIAS=Popcorn
RELEASE_KEY_PASSWORD=popcorn
RELEASE_STORE_PASSWORD=popcorn

API_ACCESS_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMjcwOTFhMGQ2ZTAxYTlmMTI0NTlhMjAzYjZjMzhiZSIsIm5iZiI6MTczOTIwMDE1OC44MDcwMDAyLCJzdWIiOiI2N2FhMTY5ZWIwMTE1M2Q2ZjQ5Mzg1MDEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.KnQAcayBK-4cJziQNcUVOmFKLXcuCRou2akTDLDww_I"
